config/routes.rb
Rails.application.routes.draw do
  get 'restaurant/google_search'

  get 'facebook/get_friends'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  get 'static_pages/home'
  get 'static_pages/private'
  get 'static_pages/logged_in'

root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      user.update_attribute(:oauth_token, auth.credentials.token)
      user.update_attribute(:oauth_expires_at, Time.at(auth.credentials.expires_at))
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        registered_user.update_attribute(:oauth_token, auth.credentials.token)
        registered_user.update_attribute(:oauth_expires_at, Time.at(auth.credentials.expires_at))
        registered_user.update_attribute(:provider, auth.provider)
        registered_user.update_attribute(:uid, auth.uid)
        return registered_user
      else
        user = User.create(name: auth.extra.raw_info.name,
                           provider: auth.provider,
                           uid: auth.uid,
                           email: auth.info.email,
                           password: Devise.friendly_token[0, 20],
                           oauth_token: auth.credentials.token,
                           oauth_expires_at: Time.at(auth.credentials.expires_at),
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController
  def get_friends
    if current_user.oauth_token
      graph = Koala::Facebook::GraphAPI.new(current_user.oauth_token)
      @user_info = graph.get_object("me")
      @friends = graph.get_connections("me", "friends")
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in @user, :event => :authentication #this will throw if @user is not activated
      flash[:success] = "Bienvenido" if is_navigational_format?
      redirect_to static_pages_private_url
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
  def google_search
    if params[:search]
      @client = GooglePlaces::Client.new(ENV['google_places'])
      # @restaurantes = @client.spots(40.434362, -3.798356, :types => ['restaurant'])
      @restaurantes = @client.spots_by_query(params[:search],:types => ['restaurant', 'cafe'])

      respond_to do |format|
        format.html
        format.js
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: :private

  def home

  end

  def logged_in

  end

  def private
    if current_user.oauth_token
      graph = Koala::Facebook::GraphAPI.new(current_user.oauth_token)
      @user_info = graph.get_object("me")
      @friends = graph.get_connections("me", "friends")
    end

    @client = GooglePlaces::Client.new(ENV['google_places'])
    # @restaurantes = @client.spots(40.434362, -3.798356, :types => ['restaurant'])
    @restaurantes = @client.spots_by_query('kaprika, en pozuelo de alarcon')

  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Recomenda"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/facebook_helper.rb
module FacebookHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/facebook/get_friends.html.erb
<h1>Facebook#get_friends</h1>
<p>Find me in app/views/facebook/get_friends.html.erb</p>

<%= @user_info.as_json.to_s + ' ' + current_user.oauth_token %>
<br/>
<% @friends.each_with_index do |friend, i| %>
    <img src="https://graph.facebook.com/<%= friend['id'] %>/picture">
    <br/>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">reCOMEnda</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to destroy_user_session_path, :method => :delete do %>
                  <i class="fa fa-sign-out"></i> Salir
              <% end %>
        <% else %>
            <li><%= link_to user_omniauth_authorize_path(:facebook) do %>
                  <i class="fa fa-facebook-square"></i> Entrar con Facebook
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield :jumbotron %>

<div id="advise-container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value.html_safe %>
      </div>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/restaurant/_google_restaurants.html.erb
<% if @restaurantes %>
    <div class="col-sm-4">
      <% @restaurantes.each do |r| %>
          <div class="col-sm-12">
            <div class="col-sm-4"><img src="<%= r.icon %>" class="img-responsive"/></div>
            <div class="col-sm-8">
              <strong><%= r.name %></strong>

              <% if r.rating %>
                  <br/>Nota google: <%= r.rating %>,
              <% end %>
              <% if r.formatted_address %>
                  <br/>
                  <small><%= r.formatted_address %></small>
              <% end %>
              <%= r.vicinity %>
              <br/>
            </div>
            <hr>
          </div>
      <% end %>
    </div>
    <div class="col-sm-4">
      <%= @restaurantes.as_json %>
    </div>
<% end %>

app/views/restaurant/google_search.html.erb
<h1>Búsqueda en google</h1>

<%= form_tag restaurant_google_search_path, :method => 'get', class: 'form form-inline' do %>

    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Restaurante Desi en Granada', id: 'inputSearchGoogle' %>
    <%= button_tag type: 'submit', class: 'btn btn-primary', name: nil do %>
        <i class="fa fa-search"></i> Buscar
    <% end %>

<% end %>

<div id="google_restaurants" class="col-sm-12">
  <%= render 'google_restaurants' %>
</div>

app/views/restaurant/google_search.js.erb
$('#google_restaurants').html('<%= escape_javascript render 'google_restaurants' %>');

app/views/static_pages/home.html.erb
<% content_for :jumbotron do %>

    <section class="jumbotron jumbotron-background">
      <div class="container">
        <% @adviseContainer = true %>
        <div id="advise-container" class="advise-home">
          <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %> alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <%= value.html_safe %>
              </div>
          <% end %>
        </div>

        <h1>rCOMENda</h1>

        <p class="margin-xxl">¿Dónde cenamos esta noche?</p>

        <p class="text-center" title="Proyectos">
          <button id="scrollDown" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-chevron-down"></span>
          </button>
        </p>
      </div>
    </section>

<% end %>

app/views/static_pages/logged_in.html.erb
<div class="jumbotron">
  logueado!!!
</div>

app/views/static_pages/private.html.erb
<div class="col-sm-4">
  <div class="col-sm-12">
    <%= link_to 'Añadir sitio', restaurant_google_search_path, class: 'btn btn-primary btn-block' %>
  </div>
  <br/>
  <% @friends.each do |friend| %>
      <img src="https://graph.facebook.com/<%= friend['id'] %>/picture"/>
      <span><%= friend['name'] %></span>
      <hr/>
  <% end %>
</div>
<div class="col-sm-4">
  <% @restaurantes.each do |r| %>
      <img src="<%= r.icon %>" class="img-responsive"/>
      <strong><%= r.name %></strong><br/>
      Nota google: <%= r.rating %>,
      <%= r.vicinity %>
      <br/>
      <hr/>
  <% end %>
</div>
<div class="col-sm-4">
  <%= @restaurantes.as_json %>
</div>